### ISSUE TITLE
Unable to auto-create a database

### ISSUE THREAD

**Issue by JoshuaBehrens** [mshepanski/quince_sqlite#2]
I am very fascinated by this library but I fail to connect to a non-existent database. This fact is understandable (as it is obvious that one fails to open anything non-existent). But this library creates the database schema so I expect it to create a whole database.

The call to [`sqlite3_open_v2`](//github.com/mshepanski/quince_sqlite/blob/00f0c7aaefd024523041f58e0270651532e88e87/src/database.cpp#L117) does neither contain a `SQLITE_OPEN_CREATE` nor a `SQLITE_OPEN_URI`. So one can't specify the mode to be ReadWriteCreate (correct me if I am wrong).

I tried it with `db.db`(missing `SQLITE_OPEN_CREATE` flag) and `file:db.db?mode=rwc`(missing `SQLITE_OPEN_URI` flag) and both don't work. I added the missing flags to the referenced call/line and it worked to auto-create the database.

I am not sure what the expected behaviour shall be and that is why I post this as an issue and not as a pull request. I am looking forward to a helping comment or an update.

**Comment by mshepanski** [comment]
This is true; quince never creates a database. (See [here](http://quince-lib.com/queries_in_c_expressions/the_quincessential_dot_points.html) and [here](http://quince-lib.com/getting_started/creating_the_database_object.html).)

I know this decision has its negative points, but I did it this way for three reasons:
1. In big systems (admittedly I am thinking more about postgresql here), database creation is often done on a separate host, and with a different authorization requirements, compared to database access (including schema creation, and table creation).
2. DBMS versioning and quince backend versioning are generally out of step. If a DBMS provides some new creation options tomorrow, you probably don't want to wait for a new quince backend that provides a wrapper for them.
3. The benefit of doing it would not be _very_ great, because the information needed to create a database doesn't overlap much with the information that quince holds (column names, column types, etc.).

**Comment by JoshuaBehrens** [comment]
I am sorry I must have overlooked your hint that one need to create a database with the given administration tool. In addition I can understand your reasons to seperate this.

Thanks for the fast help.
